---
title: "Yours in the Fantasy Analysis: Better Late Than Never"
author: "Luke Wilson"
output: 
  html_document:
    code_folding: "hide"
    includes: 
      after_body: footer.html
---

# Season Overview

[Week 1](https://lvzwilson1.github.io/weekly_report_1.html)
[Week 2](https://lvzwilson1.github.io/weekly_report_2.html)
[Week 3](https://lvzwilson1.github.io/weekly_report_3.html)
[Week 4](https://lvzwilson1.github.io/weekly_report_4.html)
[Week 5](https://lvzwilson1.github.io/weekly_report_5.html)
[Week 6](https://lvzwilson1.github.io/weekly_report_6.html)
[Week 7](https://lvzwilson1.github.io/weekly_report_7.html)
[Week 8](https://lvzwilson1.github.io/weekly_report_8.html)
[Week 9](https://lvzwilson1.github.io/weekly_report_9.html)
[Week 10](https://lvzwilson1.github.io/index.html)

```{r setup, echo=FALSE}
knitr::opts_chunk$set(fig.align = 'center')

keep(
  dat.MASTER,
  leagueDat.MASTER,
  playerscoresDat.MASTER,
  lineUps.MASTER,
  all.sched.MASTER,
  datWeekWins.LIST, 
  pyThagStats.LIST,
  merged2.LIST,
  ratingsWhores.LIST,
  thisWeek,
  sure = TRUE
)

currentWeek <- thisWeek

```


```{r data_import}
## Append the weekly datasets from the weekly reports
datWeekWins   <- plyr::rbind.fill(datWeekWins.LIST)
pyThagStats   <- plyr::rbind.fill(pyThagStats.LIST)
merged2       <- plyr::rbind.fill(merged2.LIST)
ratingsWhores <- plyr::rbind.fill(ratingsWhores.LIST)

```

## Total Wins Approach

This approach sums, for each week, how many other teams you would have beaten. A team's expected win percentage is then calculated as the number of actual possible wins, divided by the maximum number of possible wins possible, 9*number of weeks.


```{r total_week_wins}
############################ x
### Checking Total Week Wins
############################ x  

test <- merged2 %>%
  ggplot(aes(y = `Average Lost Points`, x = reportNo)) + 
  geom_line(aes(color = Team)) + 
  geom_point(aes(color = Team))
test

```
